// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ScraperDb.Models;
using System;

namespace ScraperDb.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20180521000057_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ScraperDb.Models.PortfolioInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DatePulled");

                    b.Property<double>("DayGain");

                    b.Property<double>("DayGainPercentage");

                    b.Property<double>("NetWorth");

                    b.Property<double>("TotalGain");

                    b.Property<double>("TotalGainPercentage");

                    b.HasKey("ID");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("ScraperDb.Models.StockInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CostBasis");

                    b.Property<double>("CurrentPrice");

                    b.Property<double>("DayGain");

                    b.Property<double>("DayGainPercentage");

                    b.Property<int>("Lots");

                    b.Property<double>("MarketValue");

                    b.Property<string>("Notes");

                    b.Property<int?>("PortfolioInfoID");

                    b.Property<double>("PriceChange");

                    b.Property<double>("PriceChangePercentage");

                    b.Property<double>("Shares");

                    b.Property<string>("StockSymbol");

                    b.Property<double>("TotalGain");

                    b.Property<double>("TotalGainPercentage");

                    b.HasKey("ID");

                    b.HasIndex("PortfolioInfoID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ScraperDb.Models.StockInfo", b =>
                {
                    b.HasOne("ScraperDb.Models.PortfolioInfo", "PortfolioInfo")
                        .WithMany("StockInfo")
                        .HasForeignKey("PortfolioInfoID");
                });
#pragma warning restore 612, 618
        }
    }
}
